### ISSUE TITLE
How is the final 𝛼 derived?

### ISSUE THREAD

**Issue by cuiliyuan121** [liuxiaoyu1104/SmartControl#1]
This is great work! If each decoder has a corresponding $𝛼_i$, how is the final 𝛼 used to calculate the loss obtained based on these?

**Comment by liuxiaoyu1104** [comment]
The LDM loss (defined in Equation 4) plays a crucial role in training our model. Additionally, we introduce a regularization term, as shown in Equation 5, to provide explicit supervision for each predicted control scale `𝛼_i.`

**Comment by liuxiaoyu1104** [comment]
The LDM loss (defined in Equation 4) plays a crucial role in training our model. Additionally, we introduce a regularization term, as shown in Equation 5, to provide explicit supervision for each predicted control scale `$𝛼_i$`.

**Comment by liuxiaoyu1104** [comment]
We introduce a regularization term, as shown in Equation 5, to provide explicit supervision for each predicted control scale 
**𝛼**<sub>_i_ </sub>.  Our model predict the control scale **𝛼**<sub>_1_ </sub>, **𝛼**<sub>_2_ </sub>, ..., **𝛼**<sub>_n_ </sub>. The symbol **𝛼** is a unified representation of **𝛼**<sub>_1_ </sub>, **𝛼**<sub>_2_ </sub>, ..., **𝛼**<sub>_n_ </sub>.
