### ISSUE TITLE
About the pretrained weight of smart_unet

### ISSUE THREAD

**Issue by fhzhouxdu** [liuxiaoyu1104/SmartControl#8]
Thanks for your great work! Can I ask when you will release your pre-trained weights of smart_unet?
In [https://github.com/liuxiaoyu1104/SmartControl/blob/main/smartcontrol_demo.ipynb](url) 2nd block
line 5 `smart_ckpt = "./220.ckpt"`

**Comment by fhzhouxdu** [comment]
Another question. Can you release the training script of smart_control?

**Comment by liuxiaoyu1104** [comment]
The pre-trained weights of smart_unet can be found in the **Download Models** part of readme  and training script  also release in  *How to Train* part of readme.

**Comment by liuxiaoyu1104** [comment]
The pre-trained weights of smart_unet can be found in the **Download Models** part of readme and training script also release in **How to Train** part of readme.

**Comment by fhzhouxdu** [comment]
> The pre-trained weights of smart_unet can be found in the **Download Models** part of readme and training script also release in **How to Train** part of readme.

I got it. Thank you so much!
