### ISSUE TITLE
About Control Scale Predictor implementation

### ISSUE THREAD

**Issue by mung3477** [liuxiaoyu1104/SmartControl#9]
First of all, thank you for sharing the code. It is a really interesting idea!
In your paper, Control Scale Predictor f is described as follows.

> The predictor takes _h_ and _h + h_cond_ as input and predicts a pixel-wise control scale map α. 

But I think your newly implemented forward functions use _h_ and _h + h_cond_ and _cond_.
```
h_1 = torch.cat([hidden_states, res_hidden_states[:,:c_half] + res_hidden_states[:,c_half:]], dim=1)
h_4 = torch.cat([hidden_states, res_hidden_states[:,:c_half]], dim=1)
# here
c = torch.sigmoid(c_predictor[count](torch.cat([h_1 , h_4, res_hidden_states[:,c_half:]], dim=1)))
res_hidden_states  = res_hidden_states[:,:c_half] + c* res_hidden_states[:,c_half:]       
```

Did I misunderstand sth? Or does it report better performance to use _h_ and _h + h_cond_ and _cond_ altogether?

**Comment by liuxiaoyu1104** [comment]
res_hidden_states[:,:c_half] is  skip connection of unet, hence considered as h and res_hidden_states[:,c_half:] (representing h_cond). In order to facilitate storage, both the part of the UNet skip connection and h_cond are saved in res_hidden_states.

**Comment by mung3477** [comment]
Thank you for the detailed explanation. I thought the control scale map predictor model c_predictor[count] uses h, h + h_cond, and h_cond as an input, and each stands for h_1 , h_4, res_hidden_states[:,c_half:].

**Comment by mung3477** [comment]
And also, I think this is a discussion, rather than an issue. I'll close this issue.
